# Xiang 8 Oct 2016:
# a makefile for the codes going into linear-regression

# define object files
# ALWAYS start with source code prerequisite as FIRST object file

OBJECTS= \
linear-regression.o \
module-readdata.o \
module-findNrows.o \
module-makestatistics.o \
module-writeresults.o 

# define compiler and its flags

FCOMPILER = gfortran
FFLAGS = -pg -O -g -Wall -ffixed-line-length-100

# CENTRAL PART: 
# rules to build exectuable:
# target ... : prerequisites ...
# <TAB>		Construction-commands
# favourite mistake: forget <tab> at new line of construction commands!

# target: usually file generated by programme (e.g. executable, object files).
# 	Can also be name of action to carry out, like "clean".
# prerequisite: file that is used as input to create target.

# The following is for "linking", i.e. production of an executible after
# all object files are created:

linear-regression : $(OBJECTS)
	$(FCOMPILER) $(FFLAGS) -o linear-regression $(OBJECTS)

# can drop dependencies of .o file on .f file with same root
# i.e. a.o automatically depends on a.f, so no need to specify  
%.o : %.f
	$(FCOMPILER) $(FFLAGS) -c $<

# Comparing to :
#
#linear-regression.o :
#	$(FCOMPILER) $(FFLAGS) -c $<

#module-readdata.o :
#	$(FCOMPILER) $(FFLAGS) -c module-readdata.f

#module-findNrows.o :
#	$(FCOMPILER) $(FFLAGS) -c module-findNrows.f

#module-makestatistics.o :
#	$(FCOMPILER) $(FFLAGS) -c module-makestatistics.f

#module-writeresults.o :
#	$(FCOMPILER) $(FFLAGS) -c module-writeresults.f

###############################
# These module dependencies can be defined more elegantly and quickly:
# $< is used in order to list only the *first* prerequisite (the source file)
# and not the additional prerequisites such as module or include files
# Compiler option -c: compile only and keep the .o files
# So, here the statement that _all_ .o files depend on the respective .f file:


##%.o : %.f
##	$(FCOMPILER) $(FFLAGS) -c $<

# DEFINE ALWAYS: remove all object files and programme executables 
clean :
	rm -f *.out *.o *.O *.mod *.MOD linear-regression
